Написаны функции для генерации масива и подключен main.js в index.html
htmlacademy-univer-javascript-1/2113921-kekstagram-5 pull request #3
Opened 2024-11-28 05:51 UTC by FilimonovAlexey

2024-12-03 10:33 UTC, dimohqa requested changes

2024-12-03 10:33 UTC, dimohqa commented on js/main.js
> +  const id = commentIdCounter++;
`Array.from` вторым аргументом принимает аргумент функцию, которая выполняется для каждого элемента массива (что ты и сделал). Она вызывается с аргументами элемента и индекса массива. Подобно тому как работает map:
```js
foo.map(function funcName(element, index) { ... });
``` 

С `Array.from`:
```js
Array.from({ length }, function funcName(element, index) { ... });
``` 

Соответсвенно, если ты передашь туда функцию `createComment`, то туда попадут аргументы `element` и `index`. Тогда тебе не надо будет хранить где-то счетчик идентификаторов:

```js
const createComment = (element, index) => {
  // в аргументах будут значения каждого элемента массива
}

Array.from({ length }, createComment);
```

2024-12-03 10:33 UTC, dimohqa commented on js/main.js
> +  const message = messages.join(" ");
`join` можно было сделать по месту вызова `Array.from`

2024-12-03 10:33 UTC, dimohqa commented on js/main.js
> +    name: name
Хорошей практикой является не указывать переменные в объектах, если у них совпадает нейминг:
```js
{
  id,
  avatar,
  ...
}
```

2024-12-03 10:43 UTC, FilimonovAlexey commented on js/main.js
> +    name: name
Подправил

2024-12-03 10:51 UTC, FilimonovAlexey commented on js/main.js
> +  const message = messages.join(" ");
Подправил, объединил в одну строку

2024-12-03 11:07 UTC, FilimonovAlexey commented on js/main.js
> +  const id = commentIdCounter++;
Подправил, убрал commentIdCounter для функции createComment

2024-12-03 11:10 UTC, FilimonovAlexey commented
@dimohqa Привет! Внес правки и отправил повторно pr на проверку

2024-12-04 07:35 UTC, dimohqa approved these changes

2024-12-04 07:35 UTC, merged